# 1. Import Dependencies

In [12]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

Looking in indexes: https://download.pytorch.org/whl/cu117


In [1]:
!pip install gym[box2d] pyglet

  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for box2d-py
Failed to build box2d-py
  Running setup.py install for box2d-py: started
  Running setup.py install for box2d-py: finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [16 lines of output]
  Using setuptools (version 65.5.0).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-39
  creating build\lib.win-amd64-cpython-39\Box2D
  copying library\Box2D\Box2D.py -> build\lib.win-amd64-cpython-39\Box2D
  copying library\Box2D\__init__.py -> build\lib.win-amd64-cpython-39\Box2D
  creating build\lib.win-amd64-cpython-39\Box2D\b2
  copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-cpython-39\Box2D\b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
  swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
  error: command 'swig.exe' failed: None
  [end of output]
  
  note: This error originate

In [4]:
!pip install Box2D gym

     -------------------------------------- 427.9/427.9 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for Box2D
Failed to build Box2D
  Running setup.py install for Box2D: started
  Running setup.py install for Box2D: finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [16 lines of output]
  Using setuptools (version 65.5.0).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-39
  creating build\lib.win-amd64-cpython-39\Box2D
  copying library\Box2D\Box2D.py -> build\lib.win-amd64-cpython-39\Box2D
  copying library\Box2D\__init__.py -> build\lib.win-amd64-cpython-39\Box2D
  creating build\lib.win-amd64-cpython-39\Box2D\b2
  copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-cpython-39\Box2D\b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
  swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
  error: command 'swig.exe' failed: None
  [end of output]
  
  note: This error originate

In [3]:
!pip install gym[box2d] # this one worked

  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for box2d-py: filename=box2d_py-2.3.5-cp39-cp39-win_amd64.whl size=432570 sha256=3ced3c6a12953ca76af85248205f4cd9796506c97b6118e0aadb30b4290a7035
  Stored in directory: c:\users\caleb\appdata\local\pip\cache\wheels\a4\c2\c1\076651c394f05fe60990cd85616c2d95bc1619aa113f559d7d
Successfully built box2d-py


In [7]:
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
import os

# 2. Test Environment

In [8]:
environment_name = 'CarRacing-v0'
env = gym.make(environment_name)

In [5]:
env.reset()

Track generation: 1250..1575 -> 325-tiles track


C:\Users\caleb\anaconda3\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [4]:
env.action_space

Box([-1.  0.  0.], [1. 1. 1.], (3,), float32)

In [5]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [6]:
env.render()

True

In [7]:
env.close()

In [8]:
# to understnd our environment
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset() # this gives the observations about the environment
    done = False
    score = 0
    
    while not done:
        env.render() # allows to view the environment
        action = env.action_space.sample() #generating a random action of 0 or 1 for now
        obs, reward, done, info = env.step(action) # pass through our random action to our env and we recieve info on the reward as well as a new state
        score += reward
    print('Episode:{} Score{}'.format(episode, score))
# env.close()

Track generation: 1022..1282 -> 260-tiles track
Episode:1 Score-22.779922779922924
Track generation: 1265..1586 -> 321-tiles track
Episode:2 Score-37.50000000000056
Track generation: 1072..1350 -> 278-tiles track
Episode:3 Score-27.797833935018275
Track generation: 1007..1263 -> 256-tiles track
Episode:4 Score-25.49019607843151
Track generation: 1093..1380 -> 287-tiles track
Episode:5 Score-37.06293706293761


In [9]:
env.close()

# 3.Train Model

In [18]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])

In [12]:
log_path = os.path.join('Training', 'Logs')
model = PPO('CnnPolicy', env, verbose=1, tensorboard_log=log_path)

Using cuda device
Wrapping the env in a VecTransposeImage.


In [8]:
model.learn(total_timesteps=500000)

Track generation: 1199..1505 -> 306-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1421..1780 -> 359-tiles track
Logging to Training\Logs\PPO_12
Track generation: 1133..1421 -> 288-tiles track
Track generation: 1286..1619 -> 333-tiles track
-----------------------------
| time/              |      |
|    fps             | 112  |
|    iterations      | 1    |
|    time_elapsed    | 18   |
|    total_timesteps | 2048 |
-----------------------------
Track generation: 1120..1409 -> 289-tiles track
Track generation: 1192..1494 -> 302-tiles track
---------------------------------------
| time/                   |           |
|    fps                  | 90        |
|    iterations           | 2         |
|    time_elapsed         | 45        |
|    total_timesteps      | 4096      |
| train/                  |           |
|    approx_kl            | 0.2567583 |
|    clip_fraction        | 0.519     |
|    clip_range           | 0.

# 4. Save Model

In [23]:
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_2m_Driving_model')

In [ ]:
model.save(ppo_path)

In [10]:
del model

In [24]:
model = PPO.load(ppo_path, env)

C:\Users\caleb\anaconda3\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
Exception: an integer is required (got type bytes)
  warnings.warn(
C:\Users\caleb\anaconda3\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object clip_range. Consider using `custom_objects` argument to replace this object.
Exception: an integer is required (got type bytes)
  warnings.warn(


Wrapping the env in a VecTransposeImage.


C:\Users\caleb\anaconda3\lib\site-packages\stable_baselines3\common\base_class.py:728: UserWarning: You are probably loading a model saved with SB3 < 1.7.0, we deactivated exact_match so you can save the model again to avoid issues in the future (see https://github.com/DLR-RM/stable-baselines3/issues/1233 for more info). Original error: Error(s) in loading state_dict for ActorCriticCnnPolicy:
	Missing key(s) in state_dict: "pi_features_extractor.cnn.0.weight", "pi_features_extractor.cnn.0.bias", "pi_features_extractor.cnn.2.weight", "pi_features_extractor.cnn.2.bias", "pi_features_extractor.cnn.4.weight", "pi_features_extractor.cnn.4.bias", "pi_features_extractor.linear.0.weight", "pi_features_extractor.linear.0.bias", "vf_features_extractor.cnn.0.weight", "vf_features_extractor.cnn.0.bias", "vf_features_extractor.cnn.2.weight", "vf_features_extractor.cnn.2.bias", "vf_features_extractor.cnn.4.weight", "vf_features_extractor.cnn.4.bias", "vf_features_extractor.linear.0.weight", "vf_feat

# 5. Evaluate and Test

In [14]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

C:\Users\caleb\anaconda3\lib\site-packages\stable_baselines3\common\evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Track generation: 1267..1588 -> 321-tiles track
Track generation: 1032..1300 -> 268-tiles track
Track generation: 1040..1315 -> 275-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1147..1438 -> 291-tiles track
Track generation: 1165..1465 -> 300-tiles track
Track generation: 1072..1350 -> 278-tiles track
Track generation: 1075..1348 -> 273-tiles track
Track generation: 1204..1509 -> 305-tiles track
Track generation: 1249..1565 -> 316-tiles track
Track generation: 1290..1617 -> 327-tiles track
Track generation: 1138..1435 -> 297-tiles track
Track generation: 1099..1378 -> 279-tiles track


(-89.42945990487934, 2.7988877773412937)

In [33]:
env.close()

In [30]:
# to actually test our model
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset() # gets obs of current environment
    done = False
    score = 0
    
    while not done:
        env.render() 
        action, _ = model.predict(obs) # now the action is based on the models training to predict the correct response
        obs, reward, done, info = env.step(action) # pass through our random action to our env and we recieve info on the reward as well as a new state
        score += reward
    print('Episode:{} Score{}'.format(episode, score))
# env.close()

Track generation: 1165..1464 -> 299-tiles track
Track generation: 1412..1769 -> 357-tiles track
Episode:1 Score[379.8618]
Track generation: 1379..1728 -> 349-tiles track
Track generation: 983..1233 -> 250-tiles track
Episode:2 Score[236.20203]
Track generation: 1260..1579 -> 319-tiles track
Track generation: 931..1172 -> 241-tiles track
Episode:3 Score[472.32205]
Track generation: 1172..1478 -> 306-tiles track
Track generation: 1239..1553 -> 314-tiles track
Episode:4 Score[772.1388]
Track generation: 1216..1524 -> 308-tiles track
Track generation: 1105..1385 -> 280-tiles track
retry to generate track (normal if there are not manyinstances of this message)
Track generation: 1326..1662 -> 336-tiles track
Episode:5 Score[671.9889]


In [29]:
env.close()

1